In [1]:
from Vietoris_Rips_Complex import *

In [2]:
distmat=np.loadtxt('dist_sample.txt', delimiter = ',', skiprows = 0, dtype = 'float')
print(distmat)

[[0. 2. 3. ... 5. 5. 5.]
 [2. 0. 3. ... 3. 4. 4.]
 [3. 3. 0. ... 5. 7. 6.]
 ...
 [5. 3. 5. ... 0. 4. 3.]
 [5. 4. 7. ... 4. 0. 4.]
 [5. 4. 6. ... 3. 4. 0.]]


In [3]:
_=Caculate_Vietoris_Ripscomplex_Standardalgorithm(distmat,2)

In [4]:
Show_barcode()


 0th homology: 

B1= [0,infty) : [(0,)]
B2= [0,1.0) : [(1,), (18,)]
B3= [0,2.0) : [(2,), (4,)]
B4= [0,1.0) : [(12,), (48,)]
B5= [0,1.0) : [(4,), (47,)]
B6= [0,1.0) : [(5,), (13,)]
B7= [0,2.0) : [(6,), (7,)]
B8= [0,1.0) : [(4,), (7,)]
B9= [0,3.0) : [(4,), (8,)]
B10= [0,3.0) : [(5,), (9,)]
B11= [0,3.0) : [(5,), (10,)]
B12= [0,2.0) : [(5,), (11,)]
B13= [0,1.0) : [(12,), (17,)]
B14= [0,1.0) : [(0,), (13,)]
B15= [0,3.0) : [(13,), (14,)]
B16= [0,1.0) : [(12,), (15,)]
B17= [0,1.0) : [(17,), (32,)]
B18= [0,1.0) : [(1,), (17,)]
B19= [0,1.0) : [(0,), (18,)]
B20= [0,1.0) : [(3,), (19,)]
B21= [0,1.0) : [(18,), (20,)]
B22= [0,1.0) : [(4,), (21,)]
B23= [0,1.0) : [(5,), (22,)]
B24= [0,1.0) : [(7,), (23,)]
B25= [0,3.0) : [(3,), (24,)]
B26= [0,1.0) : [(4,), (25,)]
B27= [0,1.0) : [(27,), (28,)]
B28= [0,1.0) : [(26,), (27,)]
B29= [0,1.0) : [(18,), (28,)]
B30= [0,1.0) : [(20,), (29,)]
B31= [0,1.0) : [(4,), (30,)]
B32= [0,1.0) : [(3,), (31,)]
B33= [0,1.0) : [(16,), (32,)]
B34= [0,4.0) : [(13,), (33,)]
B35